### ISSUE TITLE
Add Ethermine pools?

### ISSUE THREAD

**Issue by KiwiPopper** [WalkxCode/SaladCLI_Plus#12]
**Is your feature request related to a problem? Please describe.**
I live in Asia and Ethermine has an Asia server so I get less latency.

**Describe the solution you'd like**
Add an option for Ethermine pools.

**Describe alternatives you've considered**
I didn't think of any alternatives.

**Additional context**
Ethermine: https://ethermine.org/

**Comment by WalkxCode** [comment]
Ethermine will be added in the next release.

**Comment by KiwiPopper** [comment]
ok, got it. Thanks.

**Comment by WalkxCode** [comment]
Added. Will be released soon.
