### ISSUE TITLE
Add sex to the cli

### ISSUE THREAD

**Issue by Kylox21** [WalkxCode/SaladCLI_Plus#13]
Please salad i really Like big boob Like it would Be big and Add sex so i can Sex th e skin And Feet is Sex too Can there be a special emote for big boo skin where it will Take off cloth And show be Feet 

and I will be like mmm Sex so much I feet Yes!

Plaese

**Comment by WalkxCode** [comment]
no.

**Comment by HaveFUNRICH** [comment]
> no.

yes
