### ISSUE TITLE
When using show earning graph, the CLI+ will say your earning today is 0 dollar.

### ISSUE THREAD

**Issue by HaveFUNRICH** [WalkxCode/SaladCLI_Plus#29]
# **Describe the bug**
When using show earning graph, the CLI+ will say your earning today is 0 dollar.
\
[![version](https://img.shields.io/badge/Bug%20priority-NOTFIXED-red?style=for-the-badge)](https://github.com/WalkxCode/SaladCLI_Plus/releases/tag/v9.0)
\
[![version](https://img.shields.io/badge/Observe%20in-v9.0%20edition-brightgreen?style=for-the-badge)](https://github.com/WalkxCode/SaladCLI_Plus/releases/tag/v9.0)

## **To Reproduce**
1. Open Salad CLI+ v9
2. Select Show Earning Graph
3. Enter
4. Observe the whole bugs or the annoying existence of my bug reports contains grammar issues

## **Expected behavior**
Show Earning

## **Screenshots**
[![image](https://user-images.githubusercontent.com/60838496/124718624-7805c380-df30-11eb-88eb-86c7186f5294.png)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

## **Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider development build 21354
 - Version v9.0
 - Edition: Regular

## **Additional context ⚠️**
! only work in !
\
[![workin](https://img.shields.io/badge/Version-v9.0%20edition-brightgreen?style=for-the-badge)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by HaveFUNRICH** [comment]
Salad CLI+ version: v9.0 | July 1st 2021

**Comment by WalkxCode** [comment]
Closed due to: See discord server.

**Comment by HaveFUNRICH** [comment]
Closed due to: See this image instead of See discord server.
[![image](https://user-images.githubusercontent.com/60838496/124724621-5ad3f380-df36-11eb-97ee-372583d6dab4.png)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by WalkxCode** [comment]
a

**Comment by HaveFUNRICH** [comment]
a

**Comment by HaveFUNRICH** [comment]
Get rickroll through Gmail walky talkie.
[![image](https://user-images.githubusercontent.com/60838496/124725647-36c4e200-df37-11eb-8064-4b6bb308298c.png)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by HaveFUNRICH** [comment]
[please note walkx send this image and not me hacking walkx](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
