### ISSUE TITLE
REPLACE YOUR AUTH CODE [Solved]

### ISSUE THREAD

**Issue by SoraTogaGaming** [WalkxCode/SaladCLI_Plus#3]
If you are getting an error where it says REPLACE YOUR AUTH CODE in the config.json you need to make sure its like this 

{
	
	"salad_key": "AuthCode",
	"wallet": "WalletID"
}

and not like this 

{
	
	"salad_key": "AuthCode" ,
	"wallet": "WalletID"
}

**Comment by Walker21390** [comment]
I'll be fixing this issue today, thanks.

**Comment by WalkxCode** [comment]
This issue has been fixed in the latest release.
