### ISSUE TITLE
The setup.py says 'Access is denied' but i have enterd the right auth code? Windows 10, Chrome, Latest version.

### ISSUE THREAD

**Issue by MystreyHorse** [WalkxCode/SaladCLI_Plus#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WalkxCode** [comment]
You will get the "Access denied" error when you don't have administrator privileges or your antivirus is blocking it.

This has nothing to do with you AUTH code.

**Comment by MystreyHorse** [comment]
Hey walkx I solved its Isabella after you last helped me I contacted a
python's helper he helped me solve the problem and now its working
