### ISSUE TITLE
AST and Argparse installation

### ISSUE THREAD

**Issue by Jack92829** [WalkxCode/SaladCLI_Plus#5]
I was helping someone with an issue they had installing this, and I'm not entirely sure why you're installing AST and argparse in the setup.py
```python
os.system("python -m pip install AST")
os.system("python -m pip install argparse")
```
You never use the AST package (which hasn't been updated in years anyway), you use the `ast` package, which is a part of the standard library and therefore doesn't need any installation.
The same with `argparse`, it's part of the standard library and doesn't need installation.

This lead to the user having difficulties installing the package, as AST is well out of date and wouldn't install on python 3.9.

**Comment by WalkxCode** [comment]
Thanks for telling me, salad cli+ used ast and argparse before but It was deleted.

**Comment by WalkxCode** [comment]
```
os.system("python -m pip install AST")
os.system("python -m pip install argparse")

```

Has been removed.
