### ISSUE TITLE
How to stop it?

### ISSUE THREAD

**Issue by Vortecked** [WalkxCode/SaladCLI_Plus#6]
im probably an idiot but i cant figure out how to stop it ;-;

**Comment by Vortecked** [comment]
also, which miner should i use when it prompts me to choose the miner

**Comment by Vortecked** [comment]
> Just close the program.

ok, thanks

**Comment by WalkxCode** [comment]
> also, which miner should i use when it prompts me to choose the miner
What is your GPU?

**Comment by Vortecked** [comment]
i use a 3060 ti (and ryzen 7 3700x but im not planning to cpu mine i dont think)

**Comment by WalkxCode** [comment]
NBMiner or T-Rex miner will be the best options for you. There isn't much difference

**Comment by Vortecked** [comment]
ok, thanks

**Comment by Vortecked** [comment]
erm... sorry to bother you but this thing keeps popping up
![image](https://user-images.githubusercontent.com/71997442/116580158-f2c6b880-a8c7-11eb-9e19-9c2914fba136.png)

it pops up whenever i try to start and choose a miner. it does this with all miners

**Comment by WalkxCode** [comment]
Did your antivirus remove them by any chance?

**Comment by Vortecked** [comment]
i use avast but i didnt see anything pop up when i downloaded it, ill check the protection history thing to see if it did

**Comment by WalkxCode** [comment]
Can you check the miner folder and check in some of the folders if the miners are still there? If not your antivirus removed them.

**Comment by Vortecked** [comment]
oh, turns out it did remove something, ill go redownload

some of the folders are empty, the rest have 1/2 items in them

**Comment by WalkxCode** [comment]
Make sure you whitelist the salad cli+ folder before redownloading.

**Comment by Vortecked** [comment]
ok, this all worked. thanks!
