### ISSUE TITLE
cant start mining

### ISSUE THREAD

**Issue by TomerGamerTV** [WalkxCode/SaladCLI_Plus#8]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44266242/116795050-c636ba80-aada-11eb-9c77-5b0fb998a97e.png)
**To Reproduce**
1. start the script
2.click 6
3. get the error

**Expected behavior**
to mine

**Screenshots**
![image](https://user-images.githubusercontent.com/44266242/116795059-dcdd1180-aada-11eb-8dd2-48506819bbe0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest 

**Additional context**
i have python installed

**Comment by WalkxCode** [comment]
Install python to PATH.

**Comment by TomerGamerTV** [comment]
> Install python to PATH.

I have it install in path

**Comment by WalkxCode** [comment]
If it's installed to PATH it should run fine. Reinstall python

**Comment by TomerGamerTV** [comment]
> If it's installed to PATH it should run fine. Reinstall python

which version i should install?

**Comment by WalkxCode** [comment]
Latest version

**Comment by TomerGamerTV** [comment]
> Latest version

okay give me one sec to install..

i have it here what is the problem? 
![image](https://user-images.githubusercontent.com/44266242/116808446-7212f100-ab41-11eb-966e-7bdbab58674c.png)

**Comment by TomerGamerTV** [comment]
it should be in PATH or Path?

**Comment by WalkxCode** [comment]
PATH

**Comment by meow6969** [comment]
did you install python via the windows store? the windows store version of python does NOT add a "py" command to windows.

**Comment by TomerGamerTV** [comment]
> did you install python via the windows store? the windows store version of python does NOT add a "py" command to windows.

I downloaded it from python.org

**Comment by TomerGamerTV** [comment]
> PATH

I will check if I did it right

**Comment by TomerGamerTV** [comment]
> PATH

what is the problem? i have it here 
![image](https://user-images.githubusercontent.com/44266242/117130547-e6030280-ada8-11eb-9af3-982782589e10.png)

**Comment by meow6969** [comment]
send the output of ```python --version```

**Comment by TomerGamerTV** [comment]
> send the output of `python --version`

![image](https://user-images.githubusercontent.com/44266242/117243433-eef2e300-ae3f-11eb-9847-e39366fadfec.png)

**Comment by meow6969** [comment]
okay then, you do have everything installed but SaladCLI+ works based on the ```py``` command, which isnt added in every python install. I will make a pull request and hopefully walker will add a new release.

**Comment by TomerGamerTV** [comment]
> okay then, you do have everything installed but SaladCLI+ works based on the `py` command, which isnt added in every python install. I will make a pull request and hopefully walker will add a new release.

okay thanks
